import type { QuestionSet } from "./index.js";

export const BOOKLET_2026_QUESTION_SET: QuestionSet = {
  id: "booklet-2026-starter",
  title: "Placement Practice Starter",
  description: "A balanced starter set adapted from the supplied Aptitude and Reasoning Booklet 2026.",
  collegeId: "demo-college",
  createdAt: "2026-10-08T00:00:00.000Z",
  updatedAt: "2026-10-08T00:00:00.000Z",
  questions: [
    {
      id: "booklet-series-01",
      text: "Find the missing term: 1, 2, 9, ?, 16900",
      options: [
        { id: "a", text: "19" },
        { id: "b", text: "121" },
        { id: "c", text: "100" },
        { id: "d", text: "45" },
      ],
      correctOptionId: "c",
      topic: "logical",
      difficulty: "medium",
      timeLimitMs: 300000,
      explanation: "The booklet answer key marks option C.",
    },
    {
      id: "booklet-series-03",
      text: "Find the missing term: 6, 9, 7, 10, 8, 11, ?",
      options: [
        { id: "a", text: "14" },
        { id: "b", text: "8" },
        { id: "c", text: "9" },
        { id: "d", text: "11" },
      ],
      correctOptionId: "c",
      topic: "logical",
      difficulty: "easy",
      timeLimitMs: 300000,
      explanation: "Two interleaved sequences increase by three: 6, 7, 8, 9 and 9, 10, 11.",
    },
    {
      id: "booklet-series-10",
      text: "Find the missing term: 6, 24, 60, 120, 210, ?",
      options: [
        { id: "a", text: "363" },
        { id: "b", text: "336" },
        { id: "c", text: "346" },
        { id: "d", text: "333" },
      ],
      correctOptionId: "b",
      topic: "quantitative",
      difficulty: "medium",
      timeLimitMs: 300000,
      explanation: "The booklet answer key marks option B.",
    },
    {
      id: "booklet-coding-17",
      text: "If RANGE is coded as 12345 and RANDOM is coded as 123678, what is the code for MANGO?",
      options: [
        { id: "a", text: "82357" },
        { id: "b", text: "84629" },
        { id: "c", text: "82347" },
        { id: "d", text: "83274" },
      ],
      correctOptionId: "c",
      topic: "verbal",
      difficulty: "medium",
      timeLimitMs: 300000,
      explanation: "The booklet answer key marks option C.",
    },
    {
      id: "booklet-coding-31",
      text: "In a code language, ‘po se de’ means ‘she is good’, ‘tep re po’ means ‘good are clever’ and ‘se tep flu’ means ‘boy is clever’. Which code means ‘are’?",
      options: [
        { id: "a", text: "re" },
        { id: "b", text: "tep" },
        { id: "c", text: "po" },
        { id: "d", text: "se" },
      ],
      correctOptionId: "a",
      topic: "verbal",
      difficulty: "medium",
      timeLimitMs: 300000,
      explanation: "The booklet answer key marks option A.",
    },
    {
      id: "booklet-coding-34",
      text: "‘we try to make’ is coded as ‘76 62 56 27’; ‘make it for good’ as ‘52 75 62 26’; ‘we are good boys’ as ‘52 65 67 27’; and ‘boys try it for’ as ‘75 56 26 67’. How can ‘to try’ be written?",
      options: [
        { id: "a", text: "76, 26" },
        { id: "b", text: "56, 76" },
        { id: "c", text: "26, 56" },
        { id: "d", text: "75, 76" },
      ],
      correctOptionId: "b",
      topic: "logical",
      difficulty: "hard",
      timeLimitMs: 300000,
      explanation: "The booklet answer key marks option B.",
    },
    {
      id: "booklet-family-21",
      text: "A family consists of P, Q, R, X, Y and Z. Q is the son of R, P and R are married, Y is the brother of R, X is the daughter of P and Z is the brother of P. Who is the brother-in-law of R?",
      options: [
        { id: "a", text: "P" },
        { id: "b", text: "Z" },
        { id: "c", text: "Y" },
        { id: "d", text: "X" },
      ],
      correctOptionId: "b",
      topic: "logical",
      difficulty: "easy",
      timeLimitMs: 300000,
      explanation: "Z is the brother of P, and P is married to R.",
    },
    {
      id: "booklet-family-23",
      text: "Using the same family information, which pair is a pair of brothers?",
      options: [
        { id: "a", text: "P and X" },
        { id: "b", text: "P and Z" },
        { id: "c", text: "Q and X" },
        { id: "d", text: "R and Y" },
      ],
      correctOptionId: "b",
      topic: "logical",
      difficulty: "easy",
      timeLimitMs: 300000,
      explanation: "The booklet answer key marks option B.",
    },
    {
      id: "booklet-di-01",
      text: "Before lockdown, four ice-cream flavours contributed equally to monthly revenue of Rs.120024. After lockdown, total revenue became half. Strawberry was 33.33% and black currant was 8.33% of the post-lockdown revenue. What revenue came from strawberry and black currant together?",
      options: [
        { id: "a", text: "25000" },
        { id: "b", text: "25005" },
        { id: "c", text: "24995" },
        { id: "d", text: "25010" },
      ],
      correctOptionId: "b",
      topic: "data-interpretation",
      difficulty: "medium",
      timeLimitMs: 300000,
      explanation: "Post-lockdown revenue is Rs.60012; 33.33% + 8.33% is approximately 41.66%, giving Rs.25005 in the booklet options.",
    },
    {
      id: "booklet-di-07",
      text: "Two class tests contribute 10% each, internal assessment 30% and external exam 50%. Student A scores 45/50, 45/50, 80/100 and 160/200. What final mark does A score?",
      options: [
        { id: "a", text: "80" },
        { id: "b", text: "82" },
        { id: "c", text: "84" },
        { id: "d", text: "86" },
      ],
      correctOptionId: "b",
      topic: "data-interpretation",
      difficulty: "medium",
      timeLimitMs: 300000,
      explanation: "Weighted score: 9 + 9 + 24 + 40 = 82. The booklet answer key marks option B.",
    },
  ],
};